print("Nama: Shela")
print("Umur: 17 tahun")
print("Jurusan: PPLG")
print("Sekolah: SMK Negeri 1 Garut")
print("Cita-cita: Software Engineer")

print("Saya belajar Git dari master!")
print("Ini adalah branch latihan.")
print("Perubahan dari branch fitur-biodata!")
print("Ini perubahan dari fitur-biodata!")
print("Saya belajar membuat Pull Request!")